# syntax=docker/dockerfile:1

FROM ollama/ollama:latest

# Variáveis de otimização para CPU e pouca RAM
ENV OLLAMA_HOST=0.0.0.0
ENV OLLAMA_ORIGINS=*
ENV OLLAMA_NUM_PARALLEL=1
ENV OLLAMA_MAX_LOADED_MODELS=1
ENV OLLAMA_KEEP_ALIVE=5m
ENV OLLAMA_FLASH_ATTENTION=true
ENV OLLAMA_INTEL_GPU=false

EXPOSE 11434

VOLUME /root/.ollama

CMD ["serve"]